CREATE TABLE IF NOT EXISTS place_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    is_main BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Индекс для быстрого поиска главного фото
CREATE INDEX idx_place_photo_main ON place_photo(place_id, is_main) WHERE is_main = true;