// Code generated by protoc-gen-go. DO NOT EDIT.
// Manually generated from proto/auth.proto
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *RegisterRequest) Reset()         { *x = RegisterRequest{} }
func (x *RegisterRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *RegisterRequest) ProtoMessage()   {}
func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	return nil
}
func (x *RegisterRequest) GetLogin() string    { return x.Login }
func (x *RegisterRequest) GetPassword() string { return x.Password }
func (x *RegisterRequest) GetNickname() string { return x.Nickname }

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RegisterResponse) Reset()         { *x = RegisterResponse{} }
func (x *RegisterResponse) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *RegisterResponse) ProtoMessage()   {}
func (x *RegisterResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *RegisterResponse) GetUserId() uint64  { return x.UserId }
func (x *RegisterResponse) GetMessage() string { return x.Message }

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset()         { *x = LoginRequest{} }
func (x *LoginRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *LoginRequest) ProtoMessage()   {}
func (x *LoginRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *LoginRequest) GetLogin() string    { return x.Login }
func (x *LoginRequest) GetPassword() string { return x.Password }

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
}

func (x *LoginResponse) Reset()         { *x = LoginResponse{} }
func (x *LoginResponse) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *LoginResponse) ProtoMessage()   {}
func (x *LoginResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *LoginResponse) GetUserId() uint64    { return x.UserId }
func (x *LoginResponse) GetToken() string     { return x.Token }
func (x *LoginResponse) GetNickname() string  { return x.Nickname }
func (x *LoginResponse) GetAvatarUrl() string { return x.AvatarUrl }

type LogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LogoutRequest) Reset()         { *x = LogoutRequest{} }
func (x *LogoutRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *LogoutRequest) ProtoMessage()   {}
func (x *LogoutRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *LogoutRequest) GetToken() string { return x.Token }

type GetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserRequest) Reset()         { *x = GetUserRequest{} }
func (x *GetUserRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetUserRequest) ProtoMessage()   {}
func (x *GetUserRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetUserRequest) GetUserId() uint64 { return x.UserId }

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login     string  `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Nickname  string  `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl string  `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Role      string  `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Country   *string `protobuf:"bytes,6,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City      *string `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	About     *string `protobuf:"bytes,8,opt,name=about,proto3,oneof" json:"about,omitempty"`
	HasReviews bool   `protobuf:"varint,9,opt,name=has_reviews,json=hasReviews,proto3" json:"has_reviews,omitempty"`
	CreatedAt string  `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string  `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *User) Reset()         { *x = User{} }
func (x *User) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *User) ProtoMessage()   {}
func (x *User) ProtoReflect() protoreflect.Message { return nil }
func (x *User) GetId() uint64        { return x.Id }
func (x *User) GetLogin() string     { return x.Login }
func (x *User) GetNickname() string  { return x.Nickname }
func (x *User) GetAvatarUrl() string { return x.AvatarUrl }
func (x *User) GetRole() string      { return x.Role }

type UpdateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname *string `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	AvatarUrl *string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Country  *string `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City     *string `protobuf:"bytes,5,opt,name=city,proto3,oneof" json:"city,omitempty"`
	About    *string `protobuf:"bytes,6,opt,name=about,proto3,oneof" json:"about,omitempty"`
}

func (x *UpdateProfileRequest) Reset()         { *x = UpdateProfileRequest{} }
func (x *UpdateProfileRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *UpdateProfileRequest) ProtoMessage()   {}
func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *UpdateProfileRequest) GetUserId() uint64    { return x.UserId }
func (x *UpdateProfileRequest) GetNickname() *string  { return x.Nickname }
func (x *UpdateProfileRequest) GetAvatarUrl() *string { return x.AvatarUrl }
func (x *UpdateProfileRequest) GetCountry() *string   { return x.Country }
func (x *UpdateProfileRequest) GetCity() *string      { return x.City }
func (x *UpdateProfileRequest) GetAbout() *string     { return x.About }

type UploadAvatarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Chunk    []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *UploadAvatarRequest) Reset()         { *x = UploadAvatarRequest{} }
func (x *UploadAvatarRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *UploadAvatarRequest) ProtoMessage()   {}
func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message { return nil }

type GetAvatarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAvatarRequest) Reset()         { *x = GetAvatarRequest{} }
func (x *GetAvatarRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetAvatarRequest) ProtoMessage()   {}
func (x *GetAvatarRequest) ProtoReflect() protoreflect.Message { return nil }

type GetAvatarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *GetAvatarResponse) Reset()         { *x = GetAvatarResponse{} }
func (x *GetAvatarResponse) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetAvatarResponse) ProtoMessage()   {}
func (x *GetAvatarResponse) ProtoReflect() protoreflect.Message { return nil }

var _ = reflect.TypeOf
var _ = sync.Once{}
