// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/internal/review/repository (interfaces: ReviewRepository)
package mocks

import (
	context "context"
	models "guidely-app/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
}

type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

func (m *MockReviewRepository) Create(arg0 context.Context, arg1 *models.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockReviewRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewRepository)(nil).Create), arg0, arg1)
}

func (m *MockReviewRepository) GetByID(arg0 context.Context, arg1 uint64) (*models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockReviewRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReviewRepository)(nil).GetByID), arg0, arg1)
}

func (m *MockReviewRepository) GetByPlaceIDWithAuthor(arg0 context.Context, arg1 uint64) ([]models.ReviewWithAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlaceIDWithAuthor", arg0, arg1)
	ret0, _ := ret[0].([]models.ReviewWithAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockReviewRepositoryMockRecorder) GetByPlaceIDWithAuthor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPlaceIDWithAuthor", reflect.TypeOf((*MockReviewRepository)(nil).GetByPlaceIDWithAuthor), arg0, arg1)
}

func (m *MockReviewRepository) Delete(arg0 context.Context, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockReviewRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewRepository)(nil).Delete), arg0, arg1)
}
