FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /support ./cmd/support

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /support /support

EXPOSE 8084

CMD ["/support"]