-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname TEXT NOT NULL UNIQUE,
    avatar_url TEXT,
    password_hash TEXT NOT NULL,
    country TEXT,
    city TEXT,
    about TEXT,
    has_reviews BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS locality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country_id BIGINT NOT NULL REFERENCES country(id) ON DELETE CASCADE,
    latitude NUMERIC(10,8),
    longitude NUMERIC(11,8),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(name, country_id),
    CHECK (latitude >= -90 AND latitude <= 90),
    CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE TABLE IF NOT EXISTS place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    locality_id BIGINT REFERENCES locality(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES category(id) ON DELETE SET NULL,
    price BIGINT NOT NULL DEFAULT 0 CHECK (price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    session_token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS favorite (
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    place_id BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, place_id)
);

CREATE TABLE IF NOT EXISTS photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS place_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    photo_id BIGINT NOT NULL REFERENCES photo(id) ON DELETE CASCADE,
    is_main BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_place_photo_main ON place_photo (place_id) WHERE is_main = true;

CREATE TABLE IF NOT EXISTS review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    place_id BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    title TEXT,
    rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    visit_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, place_id)
);

CREATE TABLE IF NOT EXISTS trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (char_length(title) >= 1 AND char_length(title) <= 255),
    description TEXT,
    location TEXT,
    start_date DATE,
    end_date DATE,
    preview_url TEXT,
    created_by BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    is_public BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (start_date <= end_date)
);

CREATE TABLE IF NOT EXISTS trip_member (
    trip_id BIGINT NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (trip_id, user_id)
);

CREATE TABLE IF NOT EXISTS album (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (char_length(name) >= 1 AND char_length(name) <= 255),
    description TEXT,
    cover_photo_id BIGINT REFERENCES photo(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS album_photo (
    album_id BIGINT NOT NULL REFERENCES album(id) ON DELETE CASCADE,
    photo_id BIGINT NOT NULL REFERENCES photo(id) ON DELETE CASCADE,
    order_index SMALLINT NOT NULL DEFAULT 0 CHECK (order_index >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (album_id, photo_id)
);

CREATE TABLE IF NOT EXISTS trip_attractions (
    trip_id BIGINT NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    place_id BIGINT NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    order_index SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (trip_id, place_id)
);

ALTER TABLE "user" ADD CONSTRAINT nickname_length CHECK (char_length(nickname) >= 3 AND char_length(nickname) <= 50);

INSERT INTO country (name) VALUES
    ('Франция'), ('Италия'), ('Испания'), ('Нидерланды'), ('Индонезия'), ('Бразилия')
ON CONFLICT (name) DO NOTHING;

INSERT INTO category (name, description) VALUES
    ('Отель', 'Гостиницы и места размещения'),
    ('Музей', 'Художественные и исторические музеи'),
    ('Историческое место', 'Древние руины и достопримечательности'),
    ('Площадь', 'Городские площади'),
    ('Курорт', 'Курортные зоны и отдых')
ON CONFLICT (name) DO NOTHING;

INSERT INTO locality (name, country_id, latitude, longitude) VALUES
    ('Грамаду', (SELECT id FROM country WHERE name = 'Бразилия'), -29.3733, -50.8762),
    ('Париж', (SELECT id FROM country WHERE name = 'Франция'), 48.8566, 2.3522),
    ('Рим', (SELECT id FROM country WHERE name = 'Италия'), 41.9028, 12.4964),
    ('Барселона', (SELECT id FROM country WHERE name = 'Испания'), 41.3851, 2.1734),
    ('Амстердам', (SELECT id FROM country WHERE name = 'Нидерланды'), 52.3676, 4.9041),
    ('Бали', (SELECT id FROM country WHERE name = 'Индонезия'), -8.4095, 115.1889)
ON CONFLICT (name, country_id) DO NOTHING;

INSERT INTO place (name, description, locality_id, category_id, price) VALUES
    ('Hotel Estalagem St Hubertus', 'Очаровательный отель в Грамаду', 1, 1, 2370000),
    ('Hotel Ritta Höppner', 'Уютный отель в Грамаду', 1, 1, 1138100),
    ('Rodin Musée', 'Музей, посвящённый Огюсту Родену', 2, 2, 126900),
    ('Roman Forum', 'Древний римский форум', 3, 3, 126900),
    ('Basílica de Santa María del Pi', 'Готическая церковь в Барселоне', 4, 3, 199400),
    ('De Hallen Amsterdam', 'Культурный комплекс в Амстердаме', 5, 2, 3398800),
    ('Amnaya Resort Kuta', 'Курорт на Бали', 6, 5, 584400),
    ('Plaça Reial', 'Историческая площадь в Барселоне', 4, 4, 1236900)
ON CONFLICT (id) DO NOTHING;

INSERT INTO photo (file_path) VALUES
    ('mock/place/rcmd1.png'), ('mock/place/rcmd2.png'), ('mock/place/rcmd3.png'),
    ('mock/place/rcmd4.png'), ('mock/place/rcmd5.png'), ('mock/place/rcmd6.png'),
    ('mock/place/rcmd7.png'), ('mock/place/rcmd8.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO place_photo (place_id, photo_id, is_main) VALUES
    (1,1,true),(2,2,true),(3,3,true),(4,4,true),(5,5,true),(6,6,true),(7,7,true),(8,8,true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO "user" (nickname, avatar_url, password_hash) VALUES
    ('johnny', 'mock/user-avatar/john.jpg', 'argon2id$v=19$m=65536,t=1,p=4$LFU4f51KpaFJ85VzwIXZ2Q$NjKqQ4SfxdTnOJz22q+B8sYtNiTcOA4eozfj7mNJtnY'),
    ('jane', 'mock/user-avatar/jane.jpg', 'argon2id$v=19$m=65536,t=1,p=4$LFU4f51KpaFJ85VzwIXZ2Q$NjKqQ4SfxdTnOJz22q+B8sYtNiTcOA4eozfj7mNJtnY')
ON CONFLICT (nickname) DO NOTHING;

INSERT INTO favorite (user_id, place_id) VALUES (1,1), (1,3), (2,2), (2,4)
ON CONFLICT (user_id, place_id) DO NOTHING;

INSERT INTO review (user_id, place_id, rating, comment, visit_date) VALUES
    (1,1,5,'Отличный отель!','2025-01-10'),
    (2,3,4,'Интересный музей','2025-02-15')
ON CONFLICT (user_id, place_id) DO NOTHING;

INSERT INTO trip (title, description, location, start_date, end_date, preview_url, created_by, is_public) VALUES
    ('Поездка в Европу', 'Посещение Парижа и Рима', 'Европа', '2025-06-01', '2025-06-15', NULL, 1, true),
    ('Отдых на Бали', 'Пляжный отдых', 'Бали', '2025-07-10', '2025-07-20', NULL, 2, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO trip_member (trip_id, user_id, role) VALUES
    (1,1,'owner'), (1,2,'viewer'), (2,2,'owner')
ON CONFLICT (trip_id, user_id) DO NOTHING;

INSERT INTO album (trip_id, name, description, cover_photo_id) VALUES
    (1, 'Париж', 'Фото из Парижа', 3),
    (1, 'Рим', 'Фото из Рима', 4),
    (2, 'Бали', 'Пляжи и закаты', 7)
ON CONFLICT (id) DO NOTHING;

INSERT INTO album_photo (album_id, photo_id, order_index) VALUES
    (1,3,0), (1,8,1), (2,4,0), (3,7,0)
ON CONFLICT (album_id, photo_id) DO NOTHING;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS trip_attractions CASCADE;
DROP TABLE IF EXISTS album_photo CASCADE;
DROP TABLE IF EXISTS album CASCADE;
DROP TABLE IF EXISTS trip_member CASCADE;
DROP TABLE IF EXISTS trip CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS place_photo CASCADE;
DROP TABLE IF EXISTS photo CASCADE;
DROP TABLE IF EXISTS favorite CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS place CASCADE;
DROP TABLE IF EXISTS locality CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
-- +goose StatementEnd