-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS trip_invite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,                     
    role TEXT NOT NULL CHECK (role IN ('editor', 'viewer')),
    is_one_time BOOLEAN NOT NULL DEFAULT TRUE,      
    expires_at TIMESTAMPTZ,                        
    used_at TIMESTAMPTZ,                           
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS idx_trip_invite_token ON trip_invite(token);


CREATE INDEX IF NOT EXISTS idx_trip_invite_trip_id ON trip_invite(trip_id);


CREATE OR REPLACE FUNCTION add_trip_owner_to_members()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO trip_member (trip_id, user_id, role, joined_at)
    VALUES (NEW.id, NEW.created_by, 'owner', NOW())
    ON CONFLICT (trip_id, user_id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS after_trip_insert ON trip;
CREATE TRIGGER after_trip_insert
    AFTER INSERT ON trip
    FOR EACH ROW
    EXECUTE FUNCTION add_trip_owner_to_members();

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS after_trip_insert ON trip;
DROP FUNCTION IF EXISTS add_trip_owner_to_members();
DROP TABLE IF EXISTS trip_invite CASCADE;
-- +goose StatementEnd