-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS ticket_category (
    id SMALLINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO ticket_category (id,name) VALUES
    (1, 'Баг'),
    (2, 'Предложение'),
    (3, 'Продуктовая жалоба')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS ticket_status (
    id SNAILINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO ticket_status (id,name) VALUES 
    (1, 'Открыто'),
    (2, 'В работе'),
    (3, 'Закрыто')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS ticket (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    category_id SMALLINT NOT NULL REFERENCES ticket_category(id),
    status_id   SMALLINT NOT NULL DEFAULT 1 REFERENCES ticket_status(id),
    title       TEXT NOT NULL CHECK (char_length(title) >= 3),
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT NOT NULL REFERENCES ticket(id) ON DELETE CASCADE,
    sender_id   BIGINT NOT NULL,                     
    content     TEXT NOT NULL CHECK (char_length(content) >= 1),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_message_ticket ON message(ticket_id);
CREATE INDEX IF NOT EXISTS idx_message_created_at ON message(created_at);
CREATE INDEX IF NOT EXISTS idx_ticket_user ON ticket(user_id);
CREATE INDEX IF NOT EXISTS idx_ticket_status ON ticket(status_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS ticket_category CASCADE;
DROP TABLE IF EXISTS ticket_status CASCADE;
DROP TABLE IF EXISTS message CASCADE;
-- +goose StatementEnd