global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:9100']
        labels:
          service: 'backend'

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:9101']
        labels:
          service: 'auth'

  - job_name: 'album'
    static_configs:
      - targets: ['album:9102']
        labels:
          service: 'album'

  - job_name: 'review'
    static_configs:
      - targets: ['review:9103']
        labels:
          service: 'review'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
