// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/internal/service (interfaces: TripService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "guidely-app/internal/models"
	service "guidely-app/internal/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTripService is a mock of TripService interface.
type MockTripService struct {
	ctrl     *gomock.Controller
	recorder *MockTripServiceMockRecorder
}

// MockTripServiceMockRecorder is the mock recorder for MockTripService.
type MockTripServiceMockRecorder struct {
	mock *MockTripService
}

// NewMockTripService creates a new mock instance.
func NewMockTripService(ctrl *gomock.Controller) *MockTripService {
	mock := &MockTripService{ctrl: ctrl}
	mock.recorder = &MockTripServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripService) EXPECT() *MockTripServiceMockRecorder {
	return m.recorder
}

// AddPlaceToTrip mocks base method.
func (m *MockTripService) AddPlaceToTrip(arg0 context.Context, arg1, arg2, arg3 uint64, arg4 int16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlaceToTrip", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPlaceToTrip indicates an expected call of AddPlaceToTrip.
func (mr *MockTripServiceMockRecorder) AddPlaceToTrip(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlaceToTrip", reflect.TypeOf((*MockTripService)(nil).AddPlaceToTrip), arg0, arg1, arg2, arg3, arg4)
}

// Create mocks base method.
func (m *MockTripService) Create(arg0 context.Context, arg1 service.CreateTripInput) (*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTripServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTripService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTripService) Delete(arg0 context.Context, arg1, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTripServiceMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTripService)(nil).Delete), arg0, arg1, arg2)
}

// GetTripDetails mocks base method.
func (m *MockTripService) GetTripDetails(arg0 context.Context, arg1 uint64) (*models.Trip, []models.PlaceInTrip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripDetails", arg0, arg1)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].([]models.PlaceInTrip)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTripDetails indicates an expected call of GetTripDetails.
func (mr *MockTripServiceMockRecorder) GetTripDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripDetails", reflect.TypeOf((*MockTripService)(nil).GetTripDetails), arg0, arg1)
}

// GetTripPlaceIDs mocks base method.
func (m *MockTripService) GetTripPlaceIDs(arg0 context.Context, arg1 uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripPlaceIDs", arg0, arg1)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripPlaceIDs indicates an expected call of GetTripPlaceIDs.
func (mr *MockTripServiceMockRecorder) GetTripPlaceIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripPlaceIDs", reflect.TypeOf((*MockTripService)(nil).GetTripPlaceIDs), arg0, arg1)
}

// GetUserTrips mocks base method.
func (m *MockTripService) GetUserTrips(arg0 context.Context, arg1 uint64) ([]models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTrips", arg0, arg1)
	ret0, _ := ret[0].([]models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTrips indicates an expected call of GetUserTrips.
func (mr *MockTripServiceMockRecorder) GetUserTrips(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTrips", reflect.TypeOf((*MockTripService)(nil).GetUserTrips), arg0, arg1)
}

// RemovePlaceFromTrip mocks base method.
func (m *MockTripService) RemovePlaceFromTrip(arg0 context.Context, arg1, arg2, arg3 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePlaceFromTrip", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePlaceFromTrip indicates an expected call of RemovePlaceFromTrip.
func (mr *MockTripServiceMockRecorder) RemovePlaceFromTrip(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePlaceFromTrip", reflect.TypeOf((*MockTripService)(nil).RemovePlaceFromTrip), arg0, arg1, arg2, arg3)
}

// Update mocks base method.
func (m *MockTripService) Update(arg0 context.Context, arg1, arg2 uint64, arg3 service.UpdateTripInput) (*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTripServiceMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTripService)(nil).Update), arg0, arg1, arg2, arg3)
}
