// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/internal/service (interfaces: PlaceService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "guidely-app/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlaceService is a mock of PlaceService interface.
type MockPlaceService struct {
	ctrl     *gomock.Controller
	recorder *MockPlaceServiceMockRecorder
}

// MockPlaceServiceMockRecorder is the mock recorder for MockPlaceService.
type MockPlaceServiceMockRecorder struct {
	mock *MockPlaceService
}

// NewMockPlaceService creates a new mock instance.
func NewMockPlaceService(ctrl *gomock.Controller) *MockPlaceService {
	mock := &MockPlaceService{ctrl: ctrl}
	mock.recorder = &MockPlaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaceService) EXPECT() *MockPlaceServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockPlaceService) GetAll(arg0 context.Context) ([]models.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]models.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPlaceServiceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPlaceService)(nil).GetAll), arg0)
}

// GetDetails mocks base method.
func (m *MockPlaceService) GetDetails(arg0 context.Context, arg1, arg2 uint64) (*models.PlaceWithRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.PlaceWithRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockPlaceServiceMockRecorder) GetDetails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockPlaceService)(nil).GetDetails), arg0, arg1, arg2)
}

// GetReviews mocks base method.
func (m *MockPlaceService) GetReviews(arg0 context.Context, arg1 uint64) ([]models.ReviewWithAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviews", arg0, arg1)
	ret0, _ := ret[0].([]models.ReviewWithAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviews indicates an expected call of GetReviews.
func (mr *MockPlaceServiceMockRecorder) GetReviews(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviews", reflect.TypeOf((*MockPlaceService)(nil).GetReviews), arg0, arg1)
}
