// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/internal/service (interfaces: PlaceService,TripService,ProfileService,ReviewService)
package mocks

import (
	context "context"
	service "guidely-app/internal/service"
	models "guidely-app/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlaceService is a mock of PlaceService interface.
type MockPlaceService struct {
	ctrl     *gomock.Controller
	recorder *MockPlaceServiceMockRecorder
}

type MockPlaceServiceMockRecorder struct {
	mock *MockPlaceService
}

func NewMockPlaceService(ctrl *gomock.Controller) *MockPlaceService {
	mock := &MockPlaceService{ctrl: ctrl}
	mock.recorder = &MockPlaceServiceMockRecorder{mock}
	return mock
}

func (m *MockPlaceService) EXPECT() *MockPlaceServiceMockRecorder {
	return m.recorder
}

func (m *MockPlaceService) GetAll(arg0 context.Context) ([]models.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]models.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlaceServiceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPlaceService)(nil).GetAll), arg0)
}

func (m *MockPlaceService) GetByCategory(arg0 context.Context, arg1 uint64) ([]models.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategory", arg0, arg1)
	ret0, _ := ret[0].([]models.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlaceServiceMockRecorder) GetByCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockPlaceService)(nil).GetByCategory), arg0, arg1)
}

func (m *MockPlaceService) GetDetails(arg0 context.Context, arg1, arg2 uint64) (*models.PlaceWithRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.PlaceWithRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlaceServiceMockRecorder) GetDetails(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockPlaceService)(nil).GetDetails), arg0, arg1, arg2)
}

func (m *MockPlaceService) GetReviews(arg0 context.Context, arg1 uint64) ([]models.ReviewWithAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviews", arg0, arg1)
	ret0, _ := ret[0].([]models.ReviewWithAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlaceServiceMockRecorder) GetReviews(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviews", reflect.TypeOf((*MockPlaceService)(nil).GetReviews), arg0, arg1)
}

func (m *MockPlaceService) IsPlaceInTrip(arg0 context.Context, arg1, arg2 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPlaceInTrip", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlaceServiceMockRecorder) IsPlaceInTrip(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPlaceInTrip", reflect.TypeOf((*MockPlaceService)(nil).IsPlaceInTrip), arg0, arg1, arg2)
}

func (m *MockPlaceService) Search(arg0 context.Context, arg1 string) ([]models.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].([]models.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlaceServiceMockRecorder) Search(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPlaceService)(nil).Search), arg0, arg1)
}

// MockTripService is a mock of TripService interface.
type MockTripService struct {
	ctrl     *gomock.Controller
	recorder *MockTripServiceMockRecorder
}

type MockTripServiceMockRecorder struct {
	mock *MockTripService
}

func NewMockTripService(ctrl *gomock.Controller) *MockTripService {
	mock := &MockTripService{ctrl: ctrl}
	mock.recorder = &MockTripServiceMockRecorder{mock}
	return mock
}

func (m *MockTripService) EXPECT() *MockTripServiceMockRecorder {
	return m.recorder
}

func (m *MockTripService) Create(arg0 context.Context, arg1 service.CreateTripInput) (*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTripServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTripService)(nil).Create), arg0, arg1)
}

func (m *MockTripService) GetUserTrips(arg0 context.Context, arg1 uint64) ([]models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTrips", arg0, arg1)
	ret0, _ := ret[0].([]models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTripServiceMockRecorder) GetUserTrips(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTrips", reflect.TypeOf((*MockTripService)(nil).GetUserTrips), arg0, arg1)
}

func (m *MockTripService) GetTripDetails(arg0 context.Context, arg1 uint64) (*models.Trip, []models.PlaceInTrip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripDetails", arg0, arg1)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].([]models.PlaceInTrip)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockTripServiceMockRecorder) GetTripDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripDetails", reflect.TypeOf((*MockTripService)(nil).GetTripDetails), arg0, arg1)
}

func (m *MockTripService) Update(arg0 context.Context, arg1, arg2 uint64, arg3 service.UpdateTripInput) (*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTripServiceMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTripService)(nil).Update), arg0, arg1, arg2, arg3)
}

func (m *MockTripService) Delete(arg0 context.Context, arg1, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockTripServiceMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTripService)(nil).Delete), arg0, arg1, arg2)
}

func (m *MockTripService) GetTripPlaceIDs(arg0 context.Context, arg1 uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripPlaceIDs", arg0, arg1)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTripServiceMockRecorder) GetTripPlaceIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripPlaceIDs", reflect.TypeOf((*MockTripService)(nil).GetTripPlaceIDs), arg0, arg1)
}

func (m *MockTripService) AddPlaceToTrip(arg0 context.Context, arg1, arg2, arg3 uint64, arg4 int16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlaceToTrip", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockTripServiceMockRecorder) AddPlaceToTrip(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlaceToTrip", reflect.TypeOf((*MockTripService)(nil).AddPlaceToTrip), arg0, arg1, arg2, arg3, arg4)
}

func (m *MockTripService) RemovePlaceFromTrip(arg0 context.Context, arg1, arg2, arg3 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePlaceFromTrip", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockTripServiceMockRecorder) RemovePlaceFromTrip(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePlaceFromTrip", reflect.TypeOf((*MockTripService)(nil).RemovePlaceFromTrip), arg0, arg1, arg2, arg3)
}

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
}

type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

func (m *MockProfileService) GetProfile(arg0 context.Context, arg1 uint64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProfileServiceMockRecorder) GetProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileService)(nil).GetProfile), arg0, arg1)
}

func (m *MockProfileService) UpdateProfile(arg0 context.Context, arg1 uint64, arg2 service.UpdateProfileInput) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProfileServiceMockRecorder) UpdateProfile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileService)(nil).UpdateProfile), arg0, arg1, arg2)
}

func (m *MockProfileService) UpdateAvatar(arg0 context.Context, arg1 uint64, arg2 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockProfileServiceMockRecorder) UpdateAvatar(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockProfileService)(nil).UpdateAvatar), arg0, arg1, arg2)
}
