// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/pkg/pb/review (interfaces: ReviewServiceClient)

// Package review is a generated GoMock package.
package review

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockReviewServiceClient is a mock of ReviewServiceClient interface.
type MockReviewServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockReviewServiceClientMockRecorder
}

// MockReviewServiceClientMockRecorder is the mock recorder for MockReviewServiceClient.
type MockReviewServiceClientMockRecorder struct {
	mock *MockReviewServiceClient
}

// NewMockReviewServiceClient creates a new mock instance.
func NewMockReviewServiceClient(ctrl *gomock.Controller) *MockReviewServiceClient {
	mock := &MockReviewServiceClient{ctrl: ctrl}
	mock.recorder = &MockReviewServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewServiceClient) EXPECT() *MockReviewServiceClientMockRecorder {
	return m.recorder
}

// CreateReview mocks base method.
func (m *MockReviewServiceClient) CreateReview(arg0 context.Context, arg1 *CreateReviewRequest, arg2 ...grpc.CallOption) (*ReviewResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateReview", varargs...)
	ret0, _ := ret[0].(*ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockReviewServiceClientMockRecorder) CreateReview(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockReviewServiceClient)(nil).CreateReview), varargs...)
}

// DeleteReview mocks base method.
func (m *MockReviewServiceClient) DeleteReview(arg0 context.Context, arg1 *DeleteReviewRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteReview", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockReviewServiceClientMockRecorder) DeleteReview(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockReviewServiceClient)(nil).DeleteReview), varargs...)
}

// GetReviewsByPlace mocks base method.
func (m *MockReviewServiceClient) GetReviewsByPlace(arg0 context.Context, arg1 *GetReviewsByPlaceRequest, arg2 ...grpc.CallOption) (*GetReviewsByPlaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReviewsByPlace", varargs...)
	ret0, _ := ret[0].(*GetReviewsByPlaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewsByPlace indicates an expected call of GetReviewsByPlace.
func (mr *MockReviewServiceClientMockRecorder) GetReviewsByPlace(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsByPlace", reflect.TypeOf((*MockReviewServiceClient)(nil).GetReviewsByPlace), varargs...)
}
