// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/review.proto

package review

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlaceId       uint64                 `protobuf:"varint,2,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	VisitDate     *string                `protobuf:"bytes,6,opt,name=visit_date,json=visitDate,proto3,oneof" json:"visit_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetPlaceId() uint64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *CreateReviewRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetVisitDate() string {
	if x != nil && x.VisitDate != nil {
		return *x.VisitDate
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlaceId       uint64                 `protobuf:"varint,3,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Title         *string                `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	VisitDate     *string                `protobuf:"bytes,7,opt,name=visit_date,json=visitDate,proto3,oneof" json:"visit_date,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_proto_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewResponse) GetPlaceId() uint64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *ReviewResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ReviewResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewResponse) GetVisitDate() string {
	if x != nil && x.VisitDate != nil {
		return *x.VisitDate
	}
	return ""
}

func (x *ReviewResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReviewResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReviewId      uint64                 `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_proto_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteReviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteReviewRequest) GetReviewId() uint64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type GetReviewsByPlaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       uint64                 `protobuf:"varint,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByPlaceRequest) Reset() {
	*x = GetReviewsByPlaceRequest{}
	mi := &file_proto_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByPlaceRequest) ProtoMessage() {}

func (x *GetReviewsByPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByPlaceRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsByPlaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewsByPlaceRequest) GetPlaceId() uint64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

type GetReviewsByPlaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*ReviewWithAuthor    `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByPlaceResponse) Reset() {
	*x = GetReviewsByPlaceResponse{}
	mi := &file_proto_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByPlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByPlaceResponse) ProtoMessage() {}

func (x *GetReviewsByPlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByPlaceResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsByPlaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetReviewsByPlaceResponse) GetReviews() []*ReviewWithAuthor {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type ReviewWithAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Author        *Author                `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewWithAuthor) Reset() {
	*x = ReviewWithAuthor{}
	mi := &file_proto_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewWithAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewWithAuthor) ProtoMessage() {}

func (x *ReviewWithAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewWithAuthor.ProtoReflect.Descriptor instead.
func (*ReviewWithAuthor) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewWithAuthor) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewWithAuthor) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ReviewWithAuthor) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewWithAuthor) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewWithAuthor) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReviewWithAuthor) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_proto_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_proto_review_proto_rawDescGZIP(), []int{6}
}

func (x *Author) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Author) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

var File_proto_review_proto protoreflect.FileDescriptor

const file_proto_review_proto_rawDesc = "" +
	"\n" +
	"\x12proto/review.proto\x12\x06review\x1a\x1bgoogle/protobuf/empty.proto\"\xd3\x01\n" +
	"\x13CreateReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bplace_id\x18\x02 \x01(\x04R\aplaceId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\"\n" +
	"\n" +
	"visit_date\x18\x06 \x01(\tH\x01R\tvisitDate\x88\x01\x01B\b\n" +
	"\x06_titleB\r\n" +
	"\v_visit_date\"\x9c\x02\n" +
	"\x0eReviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x19\n" +
	"\bplace_id\x18\x03 \x01(\x04R\aplaceId\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\"\n" +
	"\n" +
	"visit_date\x18\a \x01(\tH\x01R\tvisitDate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAtB\b\n" +
	"\x06_titleB\r\n" +
	"\v_visit_date\"K\n" +
	"\x13DeleteReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x04R\breviewId\"5\n" +
	"\x18GetReviewsByPlaceRequest\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\x04R\aplaceId\"O\n" +
	"\x19GetReviewsByPlaceResponse\x122\n" +
	"\areviews\x18\x01 \x03(\v2\x18.review.ReviewWithAuthorR\areviews\"\xc0\x01\n" +
	"\x10ReviewWithAuthor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12&\n" +
	"\x06author\x18\x06 \x01(\v2\x0e.review.AuthorR\x06authorB\b\n" +
	"\x06_title\"\\\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x00R\x06avatar\x88\x01\x01B\t\n" +
	"\a_avatar2\xf3\x01\n" +
	"\rReviewService\x12C\n" +
	"\fCreateReview\x12\x1b.review.CreateReviewRequest\x1a\x16.review.ReviewResponse\x12C\n" +
	"\fDeleteReview\x12\x1b.review.DeleteReviewRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x11GetReviewsByPlace\x12 .review.GetReviewsByPlaceRequest\x1a!.review.GetReviewsByPlaceResponseB\x0fZ\rpkg/pb/reviewb\x06proto3"

var (
	file_proto_review_proto_rawDescOnce sync.Once
	file_proto_review_proto_rawDescData []byte
)

func file_proto_review_proto_rawDescGZIP() []byte {
	file_proto_review_proto_rawDescOnce.Do(func() {
		file_proto_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_review_proto_rawDesc), len(file_proto_review_proto_rawDesc)))
	})
	return file_proto_review_proto_rawDescData
}

var file_proto_review_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_review_proto_goTypes = []any{
	(*CreateReviewRequest)(nil),       // 0: review.CreateReviewRequest
	(*ReviewResponse)(nil),            // 1: review.ReviewResponse
	(*DeleteReviewRequest)(nil),       // 2: review.DeleteReviewRequest
	(*GetReviewsByPlaceRequest)(nil),  // 3: review.GetReviewsByPlaceRequest
	(*GetReviewsByPlaceResponse)(nil), // 4: review.GetReviewsByPlaceResponse
	(*ReviewWithAuthor)(nil),          // 5: review.ReviewWithAuthor
	(*Author)(nil),                    // 6: review.Author
	(*emptypb.Empty)(nil),             // 7: google.protobuf.Empty
}
var file_proto_review_proto_depIdxs = []int32{
	5, // 0: review.GetReviewsByPlaceResponse.reviews:type_name -> review.ReviewWithAuthor
	6, // 1: review.ReviewWithAuthor.author:type_name -> review.Author
	0, // 2: review.ReviewService.CreateReview:input_type -> review.CreateReviewRequest
	2, // 3: review.ReviewService.DeleteReview:input_type -> review.DeleteReviewRequest
	3, // 4: review.ReviewService.GetReviewsByPlace:input_type -> review.GetReviewsByPlaceRequest
	1, // 5: review.ReviewService.CreateReview:output_type -> review.ReviewResponse
	7, // 6: review.ReviewService.DeleteReview:output_type -> google.protobuf.Empty
	4, // 7: review.ReviewService.GetReviewsByPlace:output_type -> review.GetReviewsByPlaceResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_review_proto_init() }
func file_proto_review_proto_init() {
	if File_proto_review_proto != nil {
		return
	}
	file_proto_review_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_review_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_review_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_review_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_review_proto_rawDesc), len(file_proto_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_review_proto_goTypes,
		DependencyIndexes: file_proto_review_proto_depIdxs,
		MessageInfos:      file_proto_review_proto_msgTypes,
	}.Build()
	File_proto_review_proto = out.File
	file_proto_review_proto_goTypes = nil
	file_proto_review_proto_depIdxs = nil
}
