// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/internal/album/repository (interfaces: AlbumRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "guidely-app/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAlbumRepository is a mock of AlbumRepository interface.
type MockAlbumRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumRepositoryMockRecorder
}

// MockAlbumRepositoryMockRecorder is the mock recorder for MockAlbumRepository.
type MockAlbumRepositoryMockRecorder struct {
	mock *MockAlbumRepository
}

// NewMockAlbumRepository creates a new mock instance.
func NewMockAlbumRepository(ctrl *gomock.Controller) *MockAlbumRepository {
	mock := &MockAlbumRepository{ctrl: ctrl}
	mock.recorder = &MockAlbumRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumRepository) EXPECT() *MockAlbumRepositoryMockRecorder {
	return m.recorder
}

// AddPhoto mocks base method.
func (m *MockAlbumRepository) AddPhoto(arg0 context.Context, arg1, arg2 uint64, arg3 int16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPhoto", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPhoto indicates an expected call of AddPhoto.
func (mr *MockAlbumRepositoryMockRecorder) AddPhoto(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPhoto", reflect.TypeOf((*MockAlbumRepository)(nil).AddPhoto), arg0, arg1, arg2, arg3)
}

// Create mocks base method.
func (m *MockAlbumRepository) Create(arg0 context.Context, arg1 *models.Album) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAlbumRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlbumRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockAlbumRepository) Delete(arg0 context.Context, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlbumRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlbumRepository)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockAlbumRepository) GetByID(arg0 context.Context, arg1 uint64) (*models.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAlbumRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAlbumRepository)(nil).GetByID), arg0, arg1)
}

// GetByTrip mocks base method.
func (m *MockAlbumRepository) GetByTrip(arg0 context.Context, arg1 uint64) ([]models.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTrip", arg0, arg1)
	ret0, _ := ret[0].([]models.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTrip indicates an expected call of GetByTrip.
func (mr *MockAlbumRepositoryMockRecorder) GetByTrip(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTrip", reflect.TypeOf((*MockAlbumRepository)(nil).GetByTrip), arg0, arg1)
}

// GetPhotos mocks base method.
func (m *MockAlbumRepository) GetPhotos(arg0 context.Context, arg1 uint64) ([]models.AlbumPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotos", arg0, arg1)
	ret0, _ := ret[0].([]models.AlbumPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotos indicates an expected call of GetPhotos.
func (mr *MockAlbumRepositoryMockRecorder) GetPhotos(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotos", reflect.TypeOf((*MockAlbumRepository)(nil).GetPhotos), arg0, arg1)
}

// RemovePhoto mocks base method.
func (m *MockAlbumRepository) RemovePhoto(arg0 context.Context, arg1, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePhoto", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePhoto indicates an expected call of RemovePhoto.
func (mr *MockAlbumRepositoryMockRecorder) RemovePhoto(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePhoto", reflect.TypeOf((*MockAlbumRepository)(nil).RemovePhoto), arg0, arg1, arg2)
}

// UploadPhoto mocks base method.
func (m *MockAlbumRepository) UploadPhoto(arg0 context.Context, arg1 uint64, arg2 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPhoto", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhoto indicates an expected call of UploadPhoto.
func (mr *MockAlbumRepositoryMockRecorder) UploadPhoto(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhoto", reflect.TypeOf((*MockAlbumRepository)(nil).UploadPhoto), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockAlbumRepository) Update(arg0 context.Context, arg1 *models.Album) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAlbumRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlbumRepository)(nil).Update), arg0, arg1)
}
