// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Manually generated from proto/album.proto

package album

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// AlbumServiceClient is the client API for AlbumService service.
type AlbumServiceClient interface {
	Create(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*Album, error)
	Get(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*Album, error)
	GetByTrip(ctx context.Context, in *GetAlbumByTripRequest, opts ...grpc.CallOption) (*Album, error)
	Update(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*Album, error)
	Delete(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AlbumPhoto, error)
	RemovePhoto(ctx context.Context, in *RemovePhotoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPhotos(ctx context.Context, in *GetAlbumPhotosRequest, opts ...grpc.CallOption) (*GetAlbumPhotosResponse, error)
}

type albumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlbumServiceClient(cc grpc.ClientConnInterface) AlbumServiceClient {
	return &albumServiceClient{cc}
}

func (c *albumServiceClient) Create(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	out := new(Album)
	err := c.cc.Invoke(ctx, "/album.AlbumService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) Get(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	out := new(Album)
	err := c.cc.Invoke(ctx, "/album.AlbumService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) GetByTrip(ctx context.Context, in *GetAlbumByTripRequest, opts ...grpc.CallOption) (*Album, error) {
	out := new(Album)
	err := c.cc.Invoke(ctx, "/album.AlbumService/GetByTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) Update(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	out := new(Album)
	err := c.cc.Invoke(ctx, "/album.AlbumService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) Delete(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/album.AlbumService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AlbumPhoto, error) {
	out := new(AlbumPhoto)
	err := c.cc.Invoke(ctx, "/album.AlbumService/AddPhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) RemovePhoto(ctx context.Context, in *RemovePhotoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/album.AlbumService/RemovePhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumServiceClient) GetPhotos(ctx context.Context, in *GetAlbumPhotosRequest, opts ...grpc.CallOption) (*GetAlbumPhotosResponse, error) {
	out := new(GetAlbumPhotosResponse)
	err := c.cc.Invoke(ctx, "/album.AlbumService/GetPhotos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbumServiceServer is the server API for AlbumService service.
type AlbumServiceServer interface {
	Create(context.Context, *CreateAlbumRequest) (*Album, error)
	Get(context.Context, *GetAlbumRequest) (*Album, error)
	GetByTrip(context.Context, *GetAlbumByTripRequest) (*Album, error)
	Update(context.Context, *UpdateAlbumRequest) (*Album, error)
	Delete(context.Context, *DeleteAlbumRequest) (*emptypb.Empty, error)
	AddPhoto(context.Context, *AddPhotoRequest) (*AlbumPhoto, error)
	RemovePhoto(context.Context, *RemovePhotoRequest) (*emptypb.Empty, error)
	GetPhotos(context.Context, *GetAlbumPhotosRequest) (*GetAlbumPhotosResponse, error)
	mustEmbedUnimplementedAlbumServiceServer()
}

// UnimplementedAlbumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlbumServiceServer struct{}

func (UnimplementedAlbumServiceServer) Create(context.Context, *CreateAlbumRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAlbumServiceServer) Get(context.Context, *GetAlbumRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAlbumServiceServer) GetByTrip(context.Context, *GetAlbumByTripRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByTrip not implemented")
}
func (UnimplementedAlbumServiceServer) Update(context.Context, *UpdateAlbumRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAlbumServiceServer) Delete(context.Context, *DeleteAlbumRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAlbumServiceServer) AddPhoto(context.Context, *AddPhotoRequest) (*AlbumPhoto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPhoto not implemented")
}
func (UnimplementedAlbumServiceServer) RemovePhoto(context.Context, *RemovePhotoRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePhoto not implemented")
}
func (UnimplementedAlbumServiceServer) GetPhotos(context.Context, *GetAlbumPhotosRequest) (*GetAlbumPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhotos not implemented")
}
func (UnimplementedAlbumServiceServer) mustEmbedUnimplementedAlbumServiceServer() {}

// UnsafeAlbumServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeAlbumServiceServer interface {
	mustEmbedUnimplementedAlbumServiceServer()
}

func RegisterAlbumServiceServer(s grpc.ServiceRegistrar, srv AlbumServiceServer) {
	s.RegisterService(&AlbumService_ServiceDesc, srv)
}

func _AlbumService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/Create"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).Create(ctx, req.(*CreateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/Get"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).Get(ctx, req.(*GetAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_GetByTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumByTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).GetByTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/GetByTrip"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).GetByTrip(ctx, req.(*GetAlbumByTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/Update"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).Update(ctx, req.(*UpdateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/Delete"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).Delete(ctx, req.(*DeleteAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_AddPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).AddPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/AddPhoto"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).AddPhoto(ctx, req.(*AddPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_RemovePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).RemovePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/RemovePhoto"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).RemovePhoto(ctx, req.(*RemovePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumService_GetPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumServiceServer).GetPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/album.AlbumService/GetPhotos"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumServiceServer).GetPhotos(ctx, req.(*GetAlbumPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var AlbumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "album.AlbumService",
	HandlerType: (*AlbumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Create", Handler: _AlbumService_Create_Handler},
		{MethodName: "Get", Handler: _AlbumService_Get_Handler},
		{MethodName: "GetByTrip", Handler: _AlbumService_GetByTrip_Handler},
		{MethodName: "Update", Handler: _AlbumService_Update_Handler},
		{MethodName: "Delete", Handler: _AlbumService_Delete_Handler},
		{MethodName: "AddPhoto", Handler: _AlbumService_AddPhoto_Handler},
		{MethodName: "RemovePhoto", Handler: _AlbumService_RemovePhoto_Handler},
		{MethodName: "GetPhotos", Handler: _AlbumService_GetPhotos_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "album.proto",
}
