// Code generated by protoc-gen-go. DO NOT EDIT.
// Manually generated from proto/album.proto

package album

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TripId      uint64 `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxPhotos   int32  `protobuf:"varint,4,opt,name=max_photos,json=maxPhotos,proto3" json:"max_photos,omitempty"`
}

func (x *CreateAlbumRequest) Reset()         { *x = CreateAlbumRequest{} }
func (x *CreateAlbumRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *CreateAlbumRequest) ProtoMessage()   {}
func (x *CreateAlbumRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CreateAlbumRequest) GetTripId() uint64      { return x.TripId }
func (x *CreateAlbumRequest) GetName() string         { return x.Name }
func (x *CreateAlbumRequest) GetDescription() string  { return x.Description }
func (x *CreateAlbumRequest) GetMaxPhotos() int32     { return x.MaxPhotos }

type GetAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAlbumRequest) Reset()         { *x = GetAlbumRequest{} }
func (x *GetAlbumRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetAlbumRequest) ProtoMessage()   {}
func (x *GetAlbumRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetAlbumRequest) GetId() uint64 { return x.Id }

type GetAlbumByTripRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TripId uint64 `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
}

func (x *GetAlbumByTripRequest) Reset()         { *x = GetAlbumByTripRequest{} }
func (x *GetAlbumByTripRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetAlbumByTripRequest) ProtoMessage()   {}
func (x *GetAlbumByTripRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetAlbumByTripRequest) GetTripId() uint64 { return x.TripId }

type UpdateAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxPhotos   int32  `protobuf:"varint,4,opt,name=max_photos,json=maxPhotos,proto3" json:"max_photos,omitempty"`
}

func (x *UpdateAlbumRequest) Reset()         { *x = UpdateAlbumRequest{} }
func (x *UpdateAlbumRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *UpdateAlbumRequest) ProtoMessage()   {}
func (x *UpdateAlbumRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *UpdateAlbumRequest) GetId() uint64          { return x.Id }
func (x *UpdateAlbumRequest) GetName() string         { return x.Name }
func (x *UpdateAlbumRequest) GetDescription() string  { return x.Description }
func (x *UpdateAlbumRequest) GetMaxPhotos() int32     { return x.MaxPhotos }

type DeleteAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAlbumRequest) Reset()         { *x = DeleteAlbumRequest{} }
func (x *DeleteAlbumRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *DeleteAlbumRequest) ProtoMessage()   {}
func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DeleteAlbumRequest) GetId() uint64 { return x.Id }

type Album struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TripId       uint64  `protobuf:"varint,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Name         string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description  string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CoverPhotoId *uint64 `protobuf:"varint,5,opt,name=cover_photo_id,json=coverPhotoId,proto3,oneof" json:"cover_photo_id,omitempty"`
	MaxPhotos    int32   `protobuf:"varint,6,opt,name=max_photos,json=maxPhotos,proto3" json:"max_photos,omitempty"`
}

func (x *Album) Reset()         { *x = Album{} }
func (x *Album) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *Album) ProtoMessage()   {}
func (x *Album) ProtoReflect() protoreflect.Message { return nil }
func (x *Album) GetId() uint64           { return x.Id }
func (x *Album) GetTripId() uint64       { return x.TripId }
func (x *Album) GetName() string          { return x.Name }
func (x *Album) GetDescription() string   { return x.Description }
func (x *Album) GetCoverPhotoId() *uint64 { return x.CoverPhotoId }
func (x *Album) GetMaxPhotos() int32      { return x.MaxPhotos }

type AddPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlbumId uint64 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	PhotoId uint64 `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	Order   int32  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *AddPhotoRequest) Reset()         { *x = AddPhotoRequest{} }
func (x *AddPhotoRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *AddPhotoRequest) ProtoMessage()   {}
func (x *AddPhotoRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *AddPhotoRequest) GetAlbumId() uint64 { return x.AlbumId }
func (x *AddPhotoRequest) GetPhotoId() uint64 { return x.PhotoId }
func (x *AddPhotoRequest) GetOrder() int32    { return x.Order }

type RemovePhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlbumId uint64 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	PhotoId uint64 `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
}

func (x *RemovePhotoRequest) Reset()         { *x = RemovePhotoRequest{} }
func (x *RemovePhotoRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *RemovePhotoRequest) ProtoMessage()   {}
func (x *RemovePhotoRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *RemovePhotoRequest) GetAlbumId() uint64 { return x.AlbumId }
func (x *RemovePhotoRequest) GetPhotoId() uint64 { return x.PhotoId }

type AlbumPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlbumId    uint64 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	PhotoId    uint64 `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	OrderIndex int32  `protobuf:"varint,3,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	CreatedAt  string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *AlbumPhoto) Reset()         { *x = AlbumPhoto{} }
func (x *AlbumPhoto) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *AlbumPhoto) ProtoMessage()   {}
func (x *AlbumPhoto) ProtoReflect() protoreflect.Message { return nil }
func (x *AlbumPhoto) GetAlbumId() uint64    { return x.AlbumId }
func (x *AlbumPhoto) GetPhotoId() uint64    { return x.PhotoId }
func (x *AlbumPhoto) GetOrderIndex() int32  { return x.OrderIndex }
func (x *AlbumPhoto) GetCreatedAt() string  { return x.CreatedAt }

type GetAlbumPhotosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlbumId uint64 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
}

func (x *GetAlbumPhotosRequest) Reset()         { *x = GetAlbumPhotosRequest{} }
func (x *GetAlbumPhotosRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetAlbumPhotosRequest) ProtoMessage()   {}
func (x *GetAlbumPhotosRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *GetAlbumPhotosRequest) GetAlbumId() uint64 { return x.AlbumId }

type GetAlbumPhotosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Photos []*AlbumPhoto `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
}

func (x *GetAlbumPhotosResponse) Reset()         { *x = GetAlbumPhotosResponse{} }
func (x *GetAlbumPhotosResponse) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *GetAlbumPhotosResponse) ProtoMessage()   {}
func (x *GetAlbumPhotosResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *GetAlbumPhotosResponse) GetPhotos() []*AlbumPhoto { return x.Photos }

var _ = reflect.TypeOf
var _ = sync.Once{}
