// Code generated by MockGen. DO NOT EDIT.
// Source: guidely-app/pkg/pb/album (interfaces: AlbumServiceClient)

// Package album is a generated GoMock package.
package album

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockAlbumServiceClient is a mock of AlbumServiceClient interface.
type MockAlbumServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumServiceClientMockRecorder
}

// MockAlbumServiceClientMockRecorder is the mock recorder for MockAlbumServiceClient.
type MockAlbumServiceClientMockRecorder struct {
	mock *MockAlbumServiceClient
}

// NewMockAlbumServiceClient creates a new mock instance.
func NewMockAlbumServiceClient(ctrl *gomock.Controller) *MockAlbumServiceClient {
	mock := &MockAlbumServiceClient{ctrl: ctrl}
	mock.recorder = &MockAlbumServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumServiceClient) EXPECT() *MockAlbumServiceClientMockRecorder {
	return m.recorder
}

// AddPhoto mocks base method.
func (m *MockAlbumServiceClient) AddPhoto(arg0 context.Context, arg1 *AddPhotoRequest, arg2 ...grpc.CallOption) (*AlbumPhoto, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPhoto", varargs...)
	ret0, _ := ret[0].(*AlbumPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPhoto indicates an expected call of AddPhoto.
func (mr *MockAlbumServiceClientMockRecorder) AddPhoto(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPhoto", reflect.TypeOf((*MockAlbumServiceClient)(nil).AddPhoto), varargs...)
}

// Create mocks base method.
func (m *MockAlbumServiceClient) Create(arg0 context.Context, arg1 *CreateAlbumRequest, arg2 ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlbumServiceClientMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlbumServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockAlbumServiceClient) Delete(arg0 context.Context, arg1 *DeleteAlbumRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAlbumServiceClientMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlbumServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockAlbumServiceClient) Get(arg0 context.Context, arg1 *GetAlbumRequest, arg2 ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlbumServiceClientMockRecorder) Get(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlbumServiceClient)(nil).Get), varargs...)
}

// GetByTrip mocks base method.
func (m *MockAlbumServiceClient) GetByTrip(arg0 context.Context, arg1 *GetAlbumByTripRequest, arg2 ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByTrip", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTrip indicates an expected call of GetByTrip.
func (mr *MockAlbumServiceClientMockRecorder) GetByTrip(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTrip", reflect.TypeOf((*MockAlbumServiceClient)(nil).GetByTrip), varargs...)
}

// GetPhotos mocks base method.
func (m *MockAlbumServiceClient) GetPhotos(arg0 context.Context, arg1 *GetAlbumPhotosRequest, arg2 ...grpc.CallOption) (*GetAlbumPhotosResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPhotos", varargs...)
	ret0, _ := ret[0].(*GetAlbumPhotosResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotos indicates an expected call of GetPhotos.
func (mr *MockAlbumServiceClientMockRecorder) GetPhotos(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotos", reflect.TypeOf((*MockAlbumServiceClient)(nil).GetPhotos), varargs...)
}

// RemovePhoto mocks base method.
func (m *MockAlbumServiceClient) RemovePhoto(arg0 context.Context, arg1 *RemovePhotoRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemovePhoto", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePhoto indicates an expected call of RemovePhoto.
func (mr *MockAlbumServiceClientMockRecorder) RemovePhoto(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePhoto", reflect.TypeOf((*MockAlbumServiceClient)(nil).RemovePhoto), varargs...)
}

// Update mocks base method.
func (m *MockAlbumServiceClient) Update(arg0 context.Context, arg1 *UpdateAlbumRequest, arg2 ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlbumServiceClientMockRecorder) Update(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlbumServiceClient)(nil).Update), varargs...)
}

// UploadPhoto mocks base method.
func (m *MockAlbumServiceClient) UploadPhoto(arg0 context.Context, arg1 *UploadPhotoRequest, arg2 ...grpc.CallOption) (*UploadPhotoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadPhoto", varargs...)
	ret0, _ := ret[0].(*UploadPhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhoto indicates an expected call of UploadPhoto.
func (mr *MockAlbumServiceClientMockRecorder) UploadPhoto(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhoto", reflect.TypeOf((*MockAlbumServiceClient)(nil).UploadPhoto), varargs...)
}
