// Code generated by MockGen. DO NOT EDIT.
package album

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockAlbumServiceClient is a mock of AlbumServiceClient interface.
type MockAlbumServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumServiceClientMockRecorder
}

type MockAlbumServiceClientMockRecorder struct {
	mock *MockAlbumServiceClient
}

func NewMockAlbumServiceClient(ctrl *gomock.Controller) *MockAlbumServiceClient {
	mock := &MockAlbumServiceClient{ctrl: ctrl}
	mock.recorder = &MockAlbumServiceClientMockRecorder{mock}
	return mock
}

func (m *MockAlbumServiceClient) EXPECT() *MockAlbumServiceClientMockRecorder {
	return m.recorder
}

func (m *MockAlbumServiceClient) Create(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) Create(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlbumServiceClient)(nil).Create), varargs...)
}

func (m *MockAlbumServiceClient) Get(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) Get(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlbumServiceClient)(nil).Get), varargs...)
}

func (m *MockAlbumServiceClient) GetByTrip(ctx context.Context, in *GetAlbumByTripRequest, opts ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByTrip", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) GetByTrip(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTrip", reflect.TypeOf((*MockAlbumServiceClient)(nil).GetByTrip), varargs...)
}

func (m *MockAlbumServiceClient) Update(ctx context.Context, in *UpdateAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) Update(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlbumServiceClient)(nil).Update), varargs...)
}

func (m *MockAlbumServiceClient) Delete(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) Delete(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlbumServiceClient)(nil).Delete), varargs...)
}

func (m *MockAlbumServiceClient) AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AlbumPhoto, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPhoto", varargs...)
	ret0, _ := ret[0].(*AlbumPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) AddPhoto(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPhoto", reflect.TypeOf((*MockAlbumServiceClient)(nil).AddPhoto), varargs...)
}

func (m *MockAlbumServiceClient) RemovePhoto(ctx context.Context, in *RemovePhotoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemovePhoto", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) RemovePhoto(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePhoto", reflect.TypeOf((*MockAlbumServiceClient)(nil).RemovePhoto), varargs...)
}

func (m *MockAlbumServiceClient) GetPhotos(ctx context.Context, in *GetAlbumPhotosRequest, opts ...grpc.CallOption) (*GetAlbumPhotosResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPhotos", varargs...)
	ret0, _ := ret[0].(*GetAlbumPhotosResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAlbumServiceClientMockRecorder) GetPhotos(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotos", reflect.TypeOf((*MockAlbumServiceClient)(nil).GetPhotos), varargs...)
}
