// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2f096870DecodeGuidelyAppInternalDto(in *jlexer.Lexer, out *CreateReviewRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "place_id":
			out.PlaceID = uint64(in.Uint64())
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				*out.Title = string(in.String())
			}
		case "rating":
			out.Rating = int16(in.Int16())
		case "content":
			out.Content = string(in.String())
		case "visit_date":
			if in.IsNull() {
				in.Skip()
				out.VisitDate = nil
			} else {
				if out.VisitDate == nil {
					out.VisitDate = new(string)
				}
				*out.VisitDate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGuidelyAppInternalDto(out *jwriter.Writer, in CreateReviewRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"place_id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.PlaceID))
	}
	if in.Title != nil {
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(*in.Title))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int16(int16(in.Rating))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	if in.VisitDate != nil {
		const prefix string = ",\"visit_date\":"
		out.RawString(prefix)
		out.String(string(*in.VisitDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateReviewRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGuidelyAppInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateReviewRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGuidelyAppInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateReviewRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGuidelyAppInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateReviewRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGuidelyAppInternalDto(l, v)
}
