// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	models "guidely-app/pkg/models"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson30497fe1DecodeGuidelyAppInternalDto(in *jlexer.Lexer, out *UpdateTripRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				*out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "location":
			if in.IsNull() {
				in.Skip()
				out.Location = nil
			} else {
				if out.Location == nil {
					out.Location = new(string)
				}
				*out.Location = string(in.String())
			}
		case "start_date":
			if in.IsNull() {
				in.Skip()
				out.StartDate = nil
			} else {
				if out.StartDate == nil {
					out.StartDate = new(string)
				}
				*out.StartDate = string(in.String())
			}
		case "end_date":
			if in.IsNull() {
				in.Skip()
				out.EndDate = nil
			} else {
				if out.EndDate == nil {
					out.EndDate = new(string)
				}
				*out.EndDate = string(in.String())
			}
		case "preview":
			if in.IsNull() {
				in.Skip()
				out.Preview = nil
			} else {
				if out.Preview == nil {
					out.Preview = new(string)
				}
				*out.Preview = string(in.String())
			}
		case "is_public":
			if in.IsNull() {
				in.Skip()
				out.IsPublic = nil
			} else {
				if out.IsPublic == nil {
					out.IsPublic = new(bool)
				}
				*out.IsPublic = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto(out *jwriter.Writer, in UpdateTripRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Title != nil {
		const prefix string = ",\"title\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Title))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Description))
	}
	if in.Location != nil {
		const prefix string = ",\"location\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Location))
	}
	if in.StartDate != nil {
		const prefix string = ",\"start_date\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.StartDate))
	}
	if in.EndDate != nil {
		const prefix string = ",\"end_date\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.EndDate))
	}
	if in.Preview != nil {
		const prefix string = ",\"preview\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Preview))
	}
	if in.IsPublic != nil {
		const prefix string = ",\"is_public\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.IsPublic))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateTripRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateTripRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateTripRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateTripRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto(l, v)
}
func easyjson30497fe1DecodeGuidelyAppInternalDto1(in *jlexer.Lexer, out *TripResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "title":
			out.Title = string(in.String())
		case "location":
			if in.IsNull() {
				in.Skip()
				out.Location = nil
			} else {
				if out.Location == nil {
					out.Location = new(string)
				}
				*out.Location = string(in.String())
			}
		case "startDate":
			if in.IsNull() {
				in.Skip()
				out.StartDate = nil
			} else {
				if out.StartDate == nil {
					out.StartDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.StartDate).UnmarshalJSON(data))
				}
			}
		case "description":
			out.Description = string(in.String())
		case "endDate":
			if in.IsNull() {
				in.Skip()
				out.EndDate = nil
			} else {
				if out.EndDate == nil {
					out.EndDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.EndDate).UnmarshalJSON(data))
				}
			}
		case "preview":
			if in.IsNull() {
				in.Skip()
				out.Preview = nil
			} else {
				if out.Preview == nil {
					out.Preview = new(string)
				}
				*out.Preview = string(in.String())
			}
		case "role":
			out.Role = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto1(out *jwriter.Writer, in TripResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Location != nil {
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(*in.Location))
	}
	if in.StartDate != nil {
		const prefix string = ",\"startDate\":"
		out.RawString(prefix)
		out.Raw((*in.StartDate).MarshalJSON())
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if in.EndDate != nil {
		const prefix string = ",\"endDate\":"
		out.RawString(prefix)
		out.Raw((*in.EndDate).MarshalJSON())
	}
	if in.Preview != nil {
		const prefix string = ",\"preview\":"
		out.RawString(prefix)
		out.String(string(*in.Preview))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TripResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TripResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TripResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TripResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto1(l, v)
}
func easyjson30497fe1DecodeGuidelyAppInternalDto2(in *jlexer.Lexer, out *TripPlacesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(TripPlacesResponse, 0, 8)
			} else {
				*out = TripPlacesResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 uint64
			v1 = uint64(in.Uint64())
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto2(out *jwriter.Writer, in TripPlacesResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			out.Uint64(uint64(v3))
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v TripPlacesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TripPlacesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TripPlacesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TripPlacesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto2(l, v)
}
func easyjson30497fe1DecodeGuidelyAppInternalDto3(in *jlexer.Lexer, out *TripDetailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "title":
			out.Title = string(in.String())
		case "location":
			if in.IsNull() {
				in.Skip()
				out.Location = nil
			} else {
				if out.Location == nil {
					out.Location = new(string)
				}
				*out.Location = string(in.String())
			}
		case "startDate":
			if in.IsNull() {
				in.Skip()
				out.StartDate = nil
			} else {
				if out.StartDate == nil {
					out.StartDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.StartDate).UnmarshalJSON(data))
				}
			}
		case "endDate":
			if in.IsNull() {
				in.Skip()
				out.EndDate = nil
			} else {
				if out.EndDate == nil {
					out.EndDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.EndDate).UnmarshalJSON(data))
				}
			}
		case "preview":
			if in.IsNull() {
				in.Skip()
				out.Preview = nil
			} else {
				if out.Preview == nil {
					out.Preview = new(string)
				}
				*out.Preview = string(in.String())
			}
		case "attractions":
			if in.IsNull() {
				in.Skip()
				out.Attractions = nil
			} else {
				in.Delim('[')
				if out.Attractions == nil {
					if !in.IsDelim(']') {
						out.Attractions = make([]models.PlaceInTrip, 0, 1)
					} else {
						out.Attractions = []models.PlaceInTrip{}
					}
				} else {
					out.Attractions = (out.Attractions)[:0]
				}
				for !in.IsDelim(']') {
					var v4 models.PlaceInTrip
					easyjson30497fe1DecodeGuidelyAppPkgModels(in, &v4)
					out.Attractions = append(out.Attractions, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "role":
			out.Role = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto3(out *jwriter.Writer, in TripDetailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Location != nil {
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(*in.Location))
	}
	if in.StartDate != nil {
		const prefix string = ",\"startDate\":"
		out.RawString(prefix)
		out.Raw((*in.StartDate).MarshalJSON())
	}
	if in.EndDate != nil {
		const prefix string = ",\"endDate\":"
		out.RawString(prefix)
		out.Raw((*in.EndDate).MarshalJSON())
	}
	if in.Preview != nil {
		const prefix string = ",\"preview\":"
		out.RawString(prefix)
		out.String(string(*in.Preview))
	}
	{
		const prefix string = ",\"attractions\":"
		out.RawString(prefix)
		if in.Attractions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Attractions {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjson30497fe1EncodeGuidelyAppPkgModels(out, v6)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TripDetailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TripDetailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TripDetailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TripDetailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto3(l, v)
}
func easyjson30497fe1DecodeGuidelyAppPkgModels(in *jlexer.Lexer, out *models.PlaceInTrip) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "photo_url":
			out.PhotoURL = string(in.String())
		case "rating":
			out.Rating = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppPkgModels(out *jwriter.Writer, in models.PlaceInTrip) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"photo_url\":"
		out.RawString(prefix)
		out.String(string(in.PhotoURL))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	out.RawByte('}')
}
func easyjson30497fe1DecodeGuidelyAppInternalDto4(in *jlexer.Lexer, out *SharedTripResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "trip":
			if in.IsNull() {
				in.Skip()
				out.Trip = nil
			} else {
				if out.Trip == nil {
					out.Trip = new(models.Trip)
				}
				easyjson30497fe1DecodeGuidelyAppPkgModels1(in, out.Trip)
			}
		case "attractions":
			if in.IsNull() {
				in.Skip()
				out.Attractions = nil
			} else {
				in.Delim('[')
				if out.Attractions == nil {
					if !in.IsDelim(']') {
						out.Attractions = make([]models.PlaceInTrip, 0, 1)
					} else {
						out.Attractions = []models.PlaceInTrip{}
					}
				} else {
					out.Attractions = (out.Attractions)[:0]
				}
				for !in.IsDelim(']') {
					var v7 models.PlaceInTrip
					easyjson30497fe1DecodeGuidelyAppPkgModels(in, &v7)
					out.Attractions = append(out.Attractions, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "role":
			out.Role = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto4(out *jwriter.Writer, in SharedTripResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"trip\":"
		out.RawString(prefix[1:])
		if in.Trip == nil {
			out.RawString("null")
		} else {
			easyjson30497fe1EncodeGuidelyAppPkgModels1(out, *in.Trip)
		}
	}
	{
		const prefix string = ",\"attractions\":"
		out.RawString(prefix)
		if in.Attractions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Attractions {
				if v8 > 0 {
					out.RawByte(',')
				}
				easyjson30497fe1EncodeGuidelyAppPkgModels(out, v9)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SharedTripResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SharedTripResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SharedTripResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SharedTripResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto4(l, v)
}
func easyjson30497fe1DecodeGuidelyAppPkgModels1(in *jlexer.Lexer, out *models.Trip) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint64(in.Uint64())
		case "Title":
			out.Title = string(in.String())
		case "Description":
			out.Description = string(in.String())
		case "Location":
			if in.IsNull() {
				in.Skip()
				out.Location = nil
			} else {
				if out.Location == nil {
					out.Location = new(string)
				}
				*out.Location = string(in.String())
			}
		case "StartDate":
			if in.IsNull() {
				in.Skip()
				out.StartDate = nil
			} else {
				if out.StartDate == nil {
					out.StartDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.StartDate).UnmarshalJSON(data))
				}
			}
		case "EndDate":
			if in.IsNull() {
				in.Skip()
				out.EndDate = nil
			} else {
				if out.EndDate == nil {
					out.EndDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.EndDate).UnmarshalJSON(data))
				}
			}
		case "PreviewURL":
			if in.IsNull() {
				in.Skip()
				out.PreviewURL = nil
			} else {
				if out.PreviewURL == nil {
					out.PreviewURL = new(string)
				}
				*out.PreviewURL = string(in.String())
			}
		case "CreatedBy":
			out.CreatedBy = uint64(in.Uint64())
		case "IsPublic":
			out.IsPublic = bool(in.Bool())
		case "CreatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "UpdatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppPkgModels1(out *jwriter.Writer, in models.Trip) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"Location\":"
		out.RawString(prefix)
		if in.Location == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Location))
		}
	}
	{
		const prefix string = ",\"StartDate\":"
		out.RawString(prefix)
		if in.StartDate == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.StartDate).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"EndDate\":"
		out.RawString(prefix)
		if in.EndDate == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.EndDate).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"PreviewURL\":"
		out.RawString(prefix)
		if in.PreviewURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PreviewURL))
		}
	}
	{
		const prefix string = ",\"CreatedBy\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CreatedBy))
	}
	{
		const prefix string = ",\"IsPublic\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPublic))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjson30497fe1DecodeGuidelyAppInternalDto5(in *jlexer.Lexer, out *ShareLinkResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "share_link":
			out.ShareLink = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto5(out *jwriter.Writer, in ShareLinkResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"share_link\":"
		out.RawString(prefix[1:])
		out.String(string(in.ShareLink))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShareLinkResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShareLinkResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShareLinkResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShareLinkResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto5(l, v)
}
func easyjson30497fe1DecodeGuidelyAppInternalDto6(in *jlexer.Lexer, out *MemberResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = uint64(in.Uint64())
		case "role":
			out.Role = string(in.String())
		case "joined_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.JoinedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto6(out *jwriter.Writer, in MemberResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.UserID))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"joined_at\":"
		out.RawString(prefix)
		out.Raw((in.JoinedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MemberResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MemberResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MemberResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MemberResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto6(l, v)
}
func easyjson30497fe1DecodeGuidelyAppInternalDto7(in *jlexer.Lexer, out *CreateTripResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "preview":
			if in.IsNull() {
				in.Skip()
				out.Preview = nil
			} else {
				if out.Preview == nil {
					out.Preview = new(string)
				}
				*out.Preview = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto7(out *jwriter.Writer, in CreateTripResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	if in.Preview != nil {
		const prefix string = ",\"preview\":"
		out.RawString(prefix)
		out.String(string(*in.Preview))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTripResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTripResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTripResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTripResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto7(l, v)
}
func easyjson30497fe1DecodeGuidelyAppInternalDto8(in *jlexer.Lexer, out *CreateTripRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "location":
			if in.IsNull() {
				in.Skip()
				out.Location = nil
			} else {
				if out.Location == nil {
					out.Location = new(string)
				}
				*out.Location = string(in.String())
			}
		case "start_date":
			if in.IsNull() {
				in.Skip()
				out.StartDate = nil
			} else {
				if out.StartDate == nil {
					out.StartDate = new(string)
				}
				*out.StartDate = string(in.String())
			}
		case "end_date":
			if in.IsNull() {
				in.Skip()
				out.EndDate = nil
			} else {
				if out.EndDate == nil {
					out.EndDate = new(string)
				}
				*out.EndDate = string(in.String())
			}
		case "preview":
			if in.IsNull() {
				in.Skip()
				out.Preview = nil
			} else {
				if out.Preview == nil {
					out.Preview = new(string)
				}
				*out.Preview = string(in.String())
			}
		case "is_public":
			out.IsPublic = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson30497fe1EncodeGuidelyAppInternalDto8(out *jwriter.Writer, in CreateTripRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	if in.Location != nil {
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(*in.Location))
	}
	if in.StartDate != nil {
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.String(string(*in.StartDate))
	}
	if in.EndDate != nil {
		const prefix string = ",\"end_date\":"
		out.RawString(prefix)
		out.String(string(*in.EndDate))
	}
	if in.Preview != nil {
		const prefix string = ",\"preview\":"
		out.RawString(prefix)
		out.String(string(*in.Preview))
	}
	{
		const prefix string = ",\"is_public\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPublic))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTripRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson30497fe1EncodeGuidelyAppInternalDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTripRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson30497fe1EncodeGuidelyAppInternalDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTripRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson30497fe1DecodeGuidelyAppInternalDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTripRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson30497fe1DecodeGuidelyAppInternalDto8(l, v)
}
