// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/support/v1/support.proto

package supportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_support_v1_support_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{0}
}

type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTicketRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{3}
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{4}
}

func (x *GetTicketRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReplyAsAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyAsAdminRequest) Reset() {
	*x = ReplyAsAdminRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyAsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyAsAdminRequest) ProtoMessage() {}

func (x *ReplyAsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyAsAdminRequest.ProtoReflect.Descriptor instead.
func (*ReplyAsAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyAsAdminRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *ReplyAsAdminRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateTicketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketStatusRequest) Reset() {
	*x = UpdateTicketStatusRequest{}
	mi := &file_api_support_v1_support_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketStatusRequest) ProtoMessage() {}

func (x *UpdateTicketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTicketStatusRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *UpdateTicketStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Messages      []*Message             `protobuf:"bytes,7,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_api_support_v1_support_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{8}
}

func (x *Ticket) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ticket) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Ticket) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Ticket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ticket) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Ticket) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ticket) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AuthorType    string                 `protobuf:"bytes,3,opt,name=author_type,json=authorType,proto3" json:"author_type,omitempty"` // user, admin
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_support_v1_support_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *Message) GetAuthorType() string {
	if x != nil {
		return x.AuthorType
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_api_support_v1_support_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{10}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// По статусам
	OpenCount       int64 `protobuf:"varint,1,opt,name=open_count,json=openCount,proto3" json:"open_count,omitempty"`
	InProgressCount int64 `protobuf:"varint,2,opt,name=in_progress_count,json=inProgressCount,proto3" json:"in_progress_count,omitempty"`
	ClosedCount     int64 `protobuf:"varint,3,opt,name=closed_count,json=closedCount,proto3" json:"closed_count,omitempty"`
	// По категориям (баг/предложение/жалоба)
	ByCategory map[string]int64 `protobuf:"bytes,4,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Опционально: общее число обращений и сообщений
	TotalTickets  int64 `protobuf:"varint,5,opt,name=total_tickets,json=totalTickets,proto3" json:"total_tickets,omitempty"`
	TotalMessages int64 `protobuf:"varint,6,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_support_v1_support_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_support_v1_support_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_support_v1_support_proto_rawDescGZIP(), []int{11}
}

func (x *StatsResponse) GetOpenCount() int64 {
	if x != nil {
		return x.OpenCount
	}
	return 0
}

func (x *StatsResponse) GetInProgressCount() int64 {
	if x != nil {
		return x.InProgressCount
	}
	return 0
}

func (x *StatsResponse) GetClosedCount() int64 {
	if x != nil {
		return x.ClosedCount
	}
	return 0
}

func (x *StatsResponse) GetByCategory() map[string]int64 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *StatsResponse) GetTotalTickets() int64 {
	if x != nil {
		return x.TotalTickets
	}
	return 0
}

func (x *StatsResponse) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

var File_api_support_v1_support_proto protoreflect.FileDescriptor

const file_api_support_v1_support_proto_rawDesc = "" +
	"\n" +
	"\x1capi/support/v1/support.proto\x12\n" +
	"support.v1\"\a\n" +
	"\x05Empty\"K\n" +
	"\x13CreateTicketRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"/\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\"\x14\n" +
	"\x12ListTicketsRequest\"/\n" +
	"\x10GetTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\"E\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"F\n" +
	"\x13ReplyAsAdminRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"P\n" +
	"\x19UpdateTicketStatusRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xcf\x01\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12/\n" +
	"\bmessages\x18\a \x03(\v2\x13.support.v1.MessageR\bmessages\"\x8a\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12\x1f\n" +
	"\vauthor_type\x18\x03 \x01(\tR\n" +
	"authorType\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"C\n" +
	"\x13ListTicketsResponse\x12,\n" +
	"\atickets\x18\x01 \x03(\v2\x12.support.v1.TicketR\atickets\"\xd4\x02\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"open_count\x18\x01 \x01(\x03R\topenCount\x12*\n" +
	"\x11in_progress_count\x18\x02 \x01(\x03R\x0finProgressCount\x12!\n" +
	"\fclosed_count\x18\x03 \x01(\x03R\vclosedCount\x12J\n" +
	"\vby_category\x18\x04 \x03(\v2).support.v1.StatsResponse.ByCategoryEntryR\n" +
	"byCategory\x12#\n" +
	"\rtotal_tickets\x18\x05 \x01(\x03R\ftotalTickets\x12%\n" +
	"\x0etotal_messages\x18\x06 \x01(\x03R\rtotalMessages\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\x99\x05\n" +
	"\x0eSupportService\x12C\n" +
	"\fCreateTicket\x12\x1f.support.v1.CreateTicketRequest\x1a\x12.support.v1.Ticket\x12P\n" +
	"\rListMyTickets\x12\x1e.support.v1.ListTicketsRequest\x1a\x1f.support.v1.ListTicketsResponse\x12=\n" +
	"\tGetTicket\x12\x1c.support.v1.GetTicketRequest\x1a\x12.support.v1.Ticket\x12B\n" +
	"\vSendMessage\x12\x1e.support.v1.SendMessageRequest\x1a\x13.support.v1.Message\x128\n" +
	"\bGetStats\x12\x11.support.v1.Empty\x1a\x19.support.v1.StatsResponse\x12R\n" +
	"\x0fListOpenTickets\x12\x1e.support.v1.ListTicketsRequest\x1a\x1f.support.v1.ListTicketsResponse\x12D\n" +
	"\fReplyAsAdmin\x12\x1f.support.v1.ReplyAsAdminRequest\x1a\x13.support.v1.Message\x12O\n" +
	"\x12UpdateTicketStatus\x12%.support.v1.UpdateTicketStatusRequest\x1a\x12.support.v1.Ticket\x12H\n" +
	"\x11SubscribeToTicket\x12\x1c.support.v1.SubscribeRequest\x1a\x13.support.v1.Message0\x01B)Z'guidely-app/pkg/pb/support/v1;supportv1b\x06proto3"

var (
	file_api_support_v1_support_proto_rawDescOnce sync.Once
	file_api_support_v1_support_proto_rawDescData []byte
)

func file_api_support_v1_support_proto_rawDescGZIP() []byte {
	file_api_support_v1_support_proto_rawDescOnce.Do(func() {
		file_api_support_v1_support_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_support_v1_support_proto_rawDesc), len(file_api_support_v1_support_proto_rawDesc)))
	})
	return file_api_support_v1_support_proto_rawDescData
}

var file_api_support_v1_support_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_support_v1_support_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: support.v1.Empty
	(*CreateTicketRequest)(nil),       // 1: support.v1.CreateTicketRequest
	(*SubscribeRequest)(nil),          // 2: support.v1.SubscribeRequest
	(*ListTicketsRequest)(nil),        // 3: support.v1.ListTicketsRequest
	(*GetTicketRequest)(nil),          // 4: support.v1.GetTicketRequest
	(*SendMessageRequest)(nil),        // 5: support.v1.SendMessageRequest
	(*ReplyAsAdminRequest)(nil),       // 6: support.v1.ReplyAsAdminRequest
	(*UpdateTicketStatusRequest)(nil), // 7: support.v1.UpdateTicketStatusRequest
	(*Ticket)(nil),                    // 8: support.v1.Ticket
	(*Message)(nil),                   // 9: support.v1.Message
	(*ListTicketsResponse)(nil),       // 10: support.v1.ListTicketsResponse
	(*StatsResponse)(nil),             // 11: support.v1.StatsResponse
	nil,                               // 12: support.v1.StatsResponse.ByCategoryEntry
}
var file_api_support_v1_support_proto_depIdxs = []int32{
	9,  // 0: support.v1.Ticket.messages:type_name -> support.v1.Message
	8,  // 1: support.v1.ListTicketsResponse.tickets:type_name -> support.v1.Ticket
	12, // 2: support.v1.StatsResponse.by_category:type_name -> support.v1.StatsResponse.ByCategoryEntry
	1,  // 3: support.v1.SupportService.CreateTicket:input_type -> support.v1.CreateTicketRequest
	3,  // 4: support.v1.SupportService.ListMyTickets:input_type -> support.v1.ListTicketsRequest
	4,  // 5: support.v1.SupportService.GetTicket:input_type -> support.v1.GetTicketRequest
	5,  // 6: support.v1.SupportService.SendMessage:input_type -> support.v1.SendMessageRequest
	0,  // 7: support.v1.SupportService.GetStats:input_type -> support.v1.Empty
	3,  // 8: support.v1.SupportService.ListOpenTickets:input_type -> support.v1.ListTicketsRequest
	6,  // 9: support.v1.SupportService.ReplyAsAdmin:input_type -> support.v1.ReplyAsAdminRequest
	7,  // 10: support.v1.SupportService.UpdateTicketStatus:input_type -> support.v1.UpdateTicketStatusRequest
	2,  // 11: support.v1.SupportService.SubscribeToTicket:input_type -> support.v1.SubscribeRequest
	8,  // 12: support.v1.SupportService.CreateTicket:output_type -> support.v1.Ticket
	10, // 13: support.v1.SupportService.ListMyTickets:output_type -> support.v1.ListTicketsResponse
	8,  // 14: support.v1.SupportService.GetTicket:output_type -> support.v1.Ticket
	9,  // 15: support.v1.SupportService.SendMessage:output_type -> support.v1.Message
	11, // 16: support.v1.SupportService.GetStats:output_type -> support.v1.StatsResponse
	10, // 17: support.v1.SupportService.ListOpenTickets:output_type -> support.v1.ListTicketsResponse
	9,  // 18: support.v1.SupportService.ReplyAsAdmin:output_type -> support.v1.Message
	8,  // 19: support.v1.SupportService.UpdateTicketStatus:output_type -> support.v1.Ticket
	9,  // 20: support.v1.SupportService.SubscribeToTicket:output_type -> support.v1.Message
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_support_v1_support_proto_init() }
func file_api_support_v1_support_proto_init() {
	if File_api_support_v1_support_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_support_v1_support_proto_rawDesc), len(file_api_support_v1_support_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_support_v1_support_proto_goTypes,
		DependencyIndexes: file_api_support_v1_support_proto_depIdxs,
		MessageInfos:      file_api_support_v1_support_proto_msgTypes,
	}.Build()
	File_api_support_v1_support_proto = out.File
	file_api_support_v1_support_proto_goTypes = nil
	file_api_support_v1_support_proto_depIdxs = nil
}
